version: "3.9"

services:
  backend:
    build: ./NovaBack
    container_name: nova_backend
    ports:
      - "8000:8000"
    volumes:
      - ./NovaBack:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=NovaBack.settings
